# ========================
# App Config
# ========================
spring.application.name=urlshortener
server.port=${PORT:8080}

# ========================
# MySQL Config
# ========================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/urlshortener_db?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Dhanu@7778}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ========================
# Redis Config
# ========================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ========================
# Swagger UI
# ========================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ========================
# App Custom Config
# ========================
app.base-url=${BASE_URL:http://localhost:8080}
app.default-expiry-days=30
app.rate-limit-per-minute=10